### ISSUE TITLE
Middleware's process_request only executes before routing

### ISSUE THREAD

**Issue by rsyed83** [racker/falcon#400]
The behavior of the current "before" hook provides a handle to the "resource", the Handler object that is processing the request.

The way middleware is currently implemented (where process_request occurs only before routing) means that some before hook behavior cannot be translated into middleware.

There should be a change to the way middleware is executed that enables a middleware implementer to optionally signify that process_request should occur after routing has occurred, with access to the "resource" object.

**Comment by kgriffs** [comment]
OK, so the two cases where people care whether process_request is called before or after the route is calculated are these:

1. I want to muck with the URI or HTTP method (rewrite rules) 
2. I need access to the resource instance that will be handling the request

Are there any other cases you can think of?

Something tells me (2) is going to be more common, since many people will likely do rewriting in their web server rather than in their app. Also, having access to the resource is a richer affordance, so people will naturally use it more.

What do you think? Assuming the above make sense, we have a couple of options. First, we could simply not support (1). Or we could support it but enable (2) as the default.

**Comment by rsyed83** [comment]
Nothing comes to mind aside from these use cases for now at least.  

Do you know who was the original requester for middleware to occur before routing?  Before we change the default behavior, it might be important to understand the class of users who would be impacted by a behavior change?

Perhaps the usecase was a common enough scenario that could NOT be handled with webserver URI rewriting.

That being said, I personally don't have an objection to making (2) the default behavior, as you said access to the resource is a richer affordance.

**Comment by rsyed83** [comment]
Another update, in working on tests for my proposed change, I realized that specifying middleware execution before/after routing results in process_request getting executed out-of-order as defined by the initialization in the API class's constructor.

That's not very clean in terms of understanding execution flow, right...

**Comment by kgriffs** [comment]
The original patch was authored by @ealogar. Eduardo, can you comment?

**Comment by ealogar** [comment]
IMO a process_request mw should not be coupled with any resource. Middlewares apply to request/response and the logic of what to do after routing and having a resource defined for a particular method is some kind of logic that vary on every resource.
This is exactly what I didn't like of current before/after, They behave as a global decorator for resources but what happen when routing not success (e.g. 404 not found, 405 invalid method)... The middleware is not executed ... So, I can not use before and after for all of my middlewares.

All the middlewares I use are of that kind:
- authentication
- tracing requests
- transactions id 
- Session mw (to define global parameters for all resources)

The only point in waiting to routing to have process_request is that you will get access to params of routing and this can be useful although too much coupled to resources and routing IMO. What is the point of defining a process_request which logic dependant on routing? This behaves as a container of logic dependant of params and furthermor of resources. 

The order of middlewares behaves as if every mw class wraps the resource, that means process_request are apply in same order and process_response in reverse order. This is what naturally is expected (tracing request is executed first to trace the complete request, first arrive the process_request and at the end you go with process_response).

The solution I propose is something that I have seen in django:
- Define a extra process_resource method to be executed (when defined) before request dispatching and after routing, so the params extracted will be available. People may use process_request or process_resource based on their needs.

**Comment by kgriffs** [comment]
@rsyed83 what do you think about @ealogar's proposal to add support for an additional middleware method? I'd like to get this wrapped up over the next few days so we can release 0.2rc1...

**Comment by rsyed83** [comment]
@kgriffs my original attempt did introduce another method, but I found it difficult to track the state of the middleware stack.  It does break the flow described in the comments, where a process_request is directly paired with a corresponding process_response.

Any suggestions for how this might be achieved?  Does it make sense to execute a process_response if BOTH process_request and process_resource have been executed?  Or one or the other?

Either way, the middleware_stack structure would have to be maintained in a different way I think.

**Comment by kgriffs** [comment]
@rsyed83 Good point. This does make it a bit harder to reason about what happens when an error is raised. On the other hand, introducing a third middleware method seems like a more natural design than having an optional flag per component that determines at which point the process_request method will be executed.

With this addition, the API docstring is becoming rather long... It may make sense to move the bulk of the content over to a dedicated page in the docs. That will give us the space we need to properly explain the control flow of the framework under various circumstances.

**Comment by rsyed83** [comment]
@kgriffs fair enough, while I was a little more worried about breaking a clean calling hierarchy I'm not tied to determine the point at which process_request would get executed.

That said, I've updated the pull request to move Middleware documentation into a separate page while keeping the docstring smaller.

**Comment by kgriffs** [comment]
Fixed
